-- MUSEUM DATABASE
-- MUSEUM DATABASE
CREATE TABLE IF NOT EXISTS artworks(
    id SERIAL PRIMARY KEY,
    detail JSONB
);

CREATE TABLE IF NOT EXISTS exhibitions(
    id SERIAL PRIMARY KEY,
    detail JSONB
);
CREATE TABLE IF NOT EXISTS articles(
    id SERIAL PRIMARY KEY,
    detail JSONB
);
CREATE TABLE IF NOT EXISTS products(
    id SERIAL PRIMARY KEY,
    detail JSONB
);

CREATE TABLE IF NOT EXISTS sounds(
    id SERIAL PRIMARY KEY,
    detail JSONB
);

CREATE TABLE IF NOT EXISTS images(
    id SERIAL PRIMARY KEY,
    detail JSONB
);

CREATE TABLE IF NOT EXISTS videos(
    id SERIAL PRIMARY KEY,
    detail JSONB
);


-- USER DATABASE
CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



-- Version 2.0
CREATE TABLE IF NOT EXISTS comments
(
    id          SERIAL PRIMARY KEY,
    user_id     UUID REFERENCES users (id) ON DELETE CASCADE,
    comment     TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS status
(
    id            integer PRIMARY KEY,
    type          VARCHAR(255) NOT NULL,
    number_of_likes INTEGER,
    comment_ids    INTEGER[],
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
)


